### PR TITLE
LINK-1765, LINK-1766 | Refactor tables

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Replace all tables to use (excluding tables with collapsible content) HDS Table component.
HDS Table doesn't support clickable rows so replace them by making item name or id to work as a link.
Add column header for the tables with action buttons. Make that column to be visible only to screen readers.

## Closes
[LINK-1765](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1765)
[LINK-1766](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1766)

[LINK-1765]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1766]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr336-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr336-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr336-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr336-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr336-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr336-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr336-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr336-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr336-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by harriris-vincit — APPROVED** [review]
A test seems to be failing in the review build and the reason for the failure should be checked/fixed, but otherwise looks good now.

**Pull request merged**
