### PR TITLE
Events page remove add image with url LINK-1625

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description :sparkles:
Should not allow adding images by url.
### Closes :no_good_woman:

**[LINK-1625](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1625):**

## Screenshots :camera_flash:

Screenshot 2024-08-02 at 12 20 16

## Additional notes :spiral_notepad:

[LINK-1625]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr419-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr419-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr419-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr419-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
👍

**Pull request merged**
