### PR TITLE
LINK-1983 | Rename support page navigation

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Rename support page navigation

## Closes
[LINK-1983](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1983)

## Screenshot
Screenshot 2024-04-17 at 15 06 45

[LINK-1983]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr376-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr376-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr376-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr376-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by harriris-vincit — APPROVED** [review]
The changes themselves look good. There seem to be test failures in the review build that should be checked and possibly resolved before merging.

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr376-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr376-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr376-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
