### PR TITLE
LINK-2025 | use useAdminFormStyles hook to remove duplicate code

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Use useAdminFormStyles hook to remove duplicate code

## Closes
[LINK-2025](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2025)

[LINK-2025]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr398-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr398-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr398-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr398-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]
LGTM :100:

**Pull request merged**
