### PR TITLE
LINK-2055 Sentry fixes

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description :sparkles:

- EventSaved page should not appear if event data is not available.
- Upgrade Vite and Sentry dependencies

### Closes :no_good_woman:

**[LINK-2055](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2055):**

## Additional notes :spiral_notepad:

[LINK-2055]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr420-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr420-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr420-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr420-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr420-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
👍

**Pull request merged**
