### PR TITLE
LINK-1819 | Improve texts in cancel/delete event modals

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Improve texts in cancel/delete event modals

## Closes
[LINK-1819](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1819)

## Screenshot
Screenshot 2024-02-19 at 18 32 45

[LINK-1819]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr337-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr337-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr337-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr337-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]

**Pull request merged**
