### PR TITLE
LINK-1908 | Offer usability improvements

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Display notification for each offer
Swap description and info url fields order

## Closes
[LINK-1908](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908)

## Screenshot
Screenshot 2024-04-10 at 11 33 22

[LINK-1908]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr367-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr367-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr367-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr367-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — APPROVED** [review]

**Pull request merged**
