### PR TITLE
build: playwright initial e2e tests

### PR DESCRIPTION
**Pull request by terovirtanen**
### Closes :no_good_woman:

**[OH-52](https://helsinkisolutionoffice.atlassian.net/browse/OH-52):**

## Additional notes :spiral_notepad:

[OH-52]: https://helsinkisolutionoffice.atlassian.net/browse/OH-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr334-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr334-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr334-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr334-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by roope-ankka — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr334-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr334-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr334-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
