### PR TITLE
LINK-1932 | have only one field to define vat percentage

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Have only one field in registration/event form to define vat percentage for the price groups.

## Closes
[LINK-1932](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1932)

## Screenshot
Screenshot 2024-04-02 at 14 38 03

[LINK-1932]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr359-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr359-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr359-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — CHANGES_REQUESTED** [review]
Noticed a possible bug while testing: if I create or edit a registration and try to create registration price groups for it without having first created them for the event, I get the error "None is not a valid choice" when I try to save the changes.

**Comment by jorilindell** [comment]
> Noticed a possible bug while testing: if I create or edit a registration and try to create registration price groups for it without having first created them for the event, I get the error "None is not a valid choice" when I try to save the changes.

Very good catch. Vat percentage was missing from the payload. Added the vat percentage and issue should be fixed now.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr359-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr359-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]
LGTM, and the reported bug is fixed as well.

**Pull request merged**
