### PR TITLE
LINK-1966 | fix vitest warnings

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
LocaleRoutes: 
- Use test specific mocks instead of having common mocks variable which contains all the mocks 
- Add missing mocks to get rid of some warnings

CreateEventPage:
- Add missing mocks to get rid of some warnings

EditEventPage:
- Add missing mocks to get rid of some warnings 

mock HTMLCanvasElement.prototype.getContext function to solve accessibility test warnings

Note that there still are some warnings caused by the same name (Tuki - Tuki) in help page breadcrumbs. This issue will be solved in the LINK-1770 and can be ignored here.

## Closes
[LINK-1966](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1966)

[LINK-1966]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr381-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr381-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr381-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr381-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mikkojamG — APPROVED** [review]
👍

**Pull request merged**
