### PR TITLE
LINK-1919 | Swedish Linked Registrations instructions page

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
- Swedish Linked Registrations instructions page
- Also update content of English and Finnish Linked Registrations instructions pages

## Closes
[LINK-1919](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1919)

[LINK-1919]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr357-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr357-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — CHANGES_REQUESTED** [review]
Spotted some very minor details in the images that differ between the translations:

`src/assets/images/png/registration_instructions_6_SV.png`
- _"en länk till registreringsformuläret"_ text should start with a capital letter like it does for the other two languages

`src/assets/images/png/registration_instructions_7_EN.png`
`src/assets/images/png/registration_instructions_7_SV.png`
- texts should start with a capital letter like they do for the Finnish instructions

**Review by harriris-vincit — APPROVED** [review]
We agreed today that the minor inconsistency with the use of capital letters in the instructional images is OK for now. Therefore LGTM :+1:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr357-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr357-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
