### PR TITLE
LINK-1480 | Update NodeJs packages

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
- Bump @graphql-codegen/cli to 5.0.0, @graphql-codegen/typescript to 40.1 and @graphql-codegen/typescript-operations 4.0.1. Also regenerate GraphQl types with updated packages
- Bump @swc/core to 1.3.85 and @swc/helpers to 0.5.2
- Bump @testing-library/jest-dom to 6.1.3, @testing-library/user-event to 14.5.0, jest-axe to 8.0.0 and jest-junit to 16.0.0
- Bump eslint-config-prettier to 9.0.0, eslint-plugin-prettier to 5.0.0 and prettier to 3.0.3
- Bump formik to 2.4.4 and yup to 1.2.0
- Bump testcafe to 3.3.0 and graphql to 16.8.0. Also move testcafe related packages to dev dependencies.
- Remove extra forceReload function from TestCafe tests because new version of TestCafe seems to be able to load static files and not causing empty pages
- Bump react-router to 6.16.0
- Bump leaflet to 1.9.4
- Bump @faker-js/faker to 8.0.2 and move it to dev dependencies. Also change deprecated methods to more recent ones
- Bump @ckeditor/ckeditor5-react to 6.1.0 and @ckeditor/ckeditor5-build-classic to 39.0.2
- Bump swagger-ui-react to 5.7.1. Mock SwaggerUI component to avoid errors in import. 
- Bump hds-core and hds-react to 2.17.0
- Bump i18next to 23.5.1 and react-i18next to 13.2.2
- Bump dompurify to 3.0.5, html-tags to 3.3.1 and use-debounce to 9.0.4
- Bump @sentry/react to 7.69.0
- Bump @emotion/react to 11.11.1
- Bump axios to 1.5.0
- Bump sass to 1.67.0
- Bump snyk to 1.1220.0 and fix vulnerabilities
- Bump typescript to 5.2.2, bump also all styles and fix type errors
- Re-generate yarn.lock file

## Closes
[LINK-1480](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1480)

[LINK-1480]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mikkojamG — COMMENTED** [review]
Looks solid. For running with Docker I had a problem for testing-library dependency modules not being found. Easy fix would be to move them from devDependencies to dependencies, but can really grasp on why this happened now with these updates 🤔

**Comment by jorilindell** [comment]
> > Looks solid. For running with Docker I had a problem for testing-library dependency modules not being found. Easy fix would be to move them from devDependencies to dependencies, but can't really grasp on why this happened now with these updates 🤔
> 
> I think that removing `"**/__tests__/*",` from excludes in `tsconfig.json` causes that. I removed it because VSCode complained about missing `toBeInTheDocument` etc. asserts. That started after bumping `@testing-library/jest-dom` to the latest version.

Moved @faker-js/faker back to dependencies to fix build errors

**Comment by mikkojamG** [comment]
> > > Looks solid. For running with Docker I had a problem for testing-library dependency modules not being found. Easy fix would be to move them from devDependencies to dependencies, but can't really grasp on why this happened now with these updates 🤔
> > 
> > 
> > I think that removing `"**/__tests__/*",` from excludes in `tsconfig.json` causes that. I removed it because VSCode complained about missing `toBeInTheDocument` etc. asserts. That started after bumping `@testing-library/jest-dom` to the latest version.
> 
> Moved @faker-js/faker back to dependencies to fix build errors

Looks like I'm still getting errors 😅 
`Cannot find module '@testing-library/user-event' or its corresponding type declarations.`
`Cannot find module '@testing-library/react' or its corresponding type declarations.`
`Cannot find name 'expect'.`
`Cannot find namespace 'jest'.`

These are happening in utils and test directories

**Review by mikkojamG — APPROVED** [review]
Now runs flawlessly 👍

**Pull request merged**
