### PR TITLE
LINK-2085 | Display payment status in signups table

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Display payment status in signups table

## Closes
[LINK-2085](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2085)

## Screenshot
Screenshot 2024-06-10 at 16 36 21

[LINK-2085]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr409-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr409-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by harriris-vincit — CHANGES_REQUESTED** [review]
Perhaps the signup cancellation button could be disabled if there is a refund or cancellation in progress? I just made a change to the back-end where a 409 conflict exception is raised when trying to delete a signup or group that has an ongoing refund or cancellation.

Otherwise looks good and can approve also without the change.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr409-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr409-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by jorilindell** [comment]
> Perhaps the signup cancellation button could be disabled if there is a refund or cancellation in progress? I just made a change to the back-end where a 409 conflict exception is raised when trying to delete a signup or group that has an ongoing refund or cancellation.
> 
> Otherwise looks good and can approve also without the change.

Sounds like a good idea to disable those buttons in the case that there is a ongoing refund or cancellation. Implemented now.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr409-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr409-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr409-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]
LGTM

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr409-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr409-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
