### PR TITLE
LINK-1920 | Upgrade dependencies to the latest possible versions

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Upgrade dependencies to the latest possible versions

## Partially closes
[LINK-1920](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1920)

[LINK-1920]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by harriris-vincit** [comment]
Running `yarn audit` seems to report some critical and high vulnerabilities through indirect dependencies. Adding the most recent patched versions of the reported indirect / sub-dependencies to `resolutions` in `package.json` seems to fix the issues mentioned in this attached file: [yarn_audit.txt](https://github.com/City-of-Helsinki/linkedcomponents-ui/files/14854921/yarn_audit.txt).

Otherwise looks good and works well when testing.

**Review by harriris-vincit — CHANGES_REQUESTED** [review]
Running yarn audit seems to report some critical and high vulnerabilities through indirect dependencies. Adding the most recent patched versions of the reported indirect / sub-dependencies to resolutions in package.json seems to fix the issues mentioned in this attached file: [yarn_audit.txt](https://github.com/City-of-Helsinki/linkedcomponents-ui/files/14854921/yarn_audit.txt).

Otherwise looks good and works well when testing.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr353-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr353-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
