### PR TITLE
LINK-1948 | allow registration admin to signup to a closed registration

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Allow registration admin to signup to a closed registration in the case that there still are available seats

## Closes
[LINK-1948](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1948)

[LINK-1948]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr378-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr378-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — APPROVED** [review]

**Review by harriris-vincit — COMMENTED** [review]
@jorilindell The back-end changes have been merged and they allow a registration.created_by event admin and a substitute user to create signups to a closed registration in addition to registration admin and a superuser.

**Comment by jorilindell** [comment]
> @jorilindell The back-end changes have been merged and they allow a registration.created_by event admin and a substitute user to create signups to a closed registration in addition to registration admin and a superuser.

@harriris-vincit Modified checkCanUserSignupAfterSignupIsEnded function to allow a registration.created_by event admin and substitute user to create signups to a closed registration

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr378-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by harriris-vincit — APPROVED** [review]
Looks good now

**Pull request merged**
