### PR TITLE
LINK-1990 | update accessibility statement

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Update accessibility statement page content to match current situation.

## Closes
[LINK-1990](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1990)

[LINK-1990]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr405-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr405-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by jorilindell** [comment]
> https://www.webaccessibility.fi/

Absolutely. I started using the English link in the English accessibility statement page.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr405-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr405-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
