### PR TITLE
LINK-1951 | Fine-tune external user instruction text

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Fine-tune external user instruction text

## Closes
[LINK-1951](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1951)

## Screenshot
Screenshot 2024-04-15 at 9 05 56

[LINK-1951]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr374-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr374-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by harriris-vincit — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr374-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr374-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
