### PR TITLE
LINK-1891 | Fix failing tests

### PR DESCRIPTION
**Pull request by jorilindell**
## Description
Fix failing test by is caused by the missing prop in the test file.
Fix failing e2e tests.
Add e2e tests for the footer links which still are missing tests

## Closes
[LINK-1891](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1891)

[LINK-1891]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr330-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr330-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://linkedcomponents-pr330-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Review by harriris-vincit — APPROVED** [review]

**Comment by jorilindell** [comment]
> ## e2e tests result is **failed** for https://linkedcomponents-pr330-ui.dev.hel.ninja 😿💢💥💥

Nice to have e2e-tests as a part of the review pipeline. I fixed failing e2e-tests and added also some new one for the new footer links. Hopefully the pipeline will pass after these changes.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr330-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr330-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
