### PR TITLE
LINK-1908 | Offer price groups for event offer

### PR DESCRIPTION
**Pull request by jorilindell**
## Description :sparkles:
- Add "Tapahtumalle luodaan Linked Registration -ilmoittautuminen" checkbox to event form. Show offer price groups if checkbox is checked. Offer price group contains same fields as registration price groups in registration form
- Copy offer price groups to a new registrations

## Closes
[LINK-1908](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908)

## Screenshot
Screenshot 2024-03-13 at 13 43 56

[LINK-1908]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr350-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr350-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr350-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mikkojamG — APPROVED** [review]
Looks good, noticed that here is one Sonar issue 🙂

**Review by harriris-vincit — APPROVED** [review]
Looks good and also worked as expected when testing.

**Comment by terovirtanen** [comment]
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr350-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://linkedcomponents-pr350-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
